- doc/gsim/edwards_fah_2013a.rst
- doc/gsim/edwards_fah_2013f.rst
- openquake/hazardlib/gsim/edwards_fah_2013a.py
- openquake/hazardlib/gsim/edwards_fah_2013f.py
- openquake/hazardlib/tests/gsim/edwards_faeh_2013_alpine_test.py
- openquake/hazardlib/tests/gsim/edwards_faeh_2013_foreland_test.py
This supersedes https://github.com/gem/oq-hazardlib/pull/275. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/181
> Renamed some GMPEs

- debian/changelog
- packager.sh
2 minor fixes on the development packaging part.
> Release 1.3

- openquake/hazardlib/gsim/abrahamson_2014.py
This PR fixes a small bug in the soil depth term of the ASK2014 GMPE. Tests are green https://ci.openquake.org/job/zdevel_oq-hazardlib/243/
> Fixes a minor bug in the soil depth term

- packager.sh
retrieve version from __init__.py fixed
> Fix ini vers2

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/gsim/base.py
- openquake/hazardlib/tests/acceptance/peer_test.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
See https://bugs.launchpad.net/oq-engine/+bug/1448124. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/283/
> Compact representation for the hazard curves

- packager.sh
Improve consistency of CI tests using dependencies packages build starting from the same commit used for dev tests.
> [WIP] Ci interpkg consistency improvement.

- debian/changelog
- packager.sh
> Engine 1.4

- openquake/baselib/performance.py
- openquake/baselib/tests/performance_test.py
- openquake/hazardlib/calc/hazard_curve.py
See https://bugs.launchpad.net/oq-engine/+bug/1417446.
The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/345
Documentation will be added in a separated pull request.
> Include a monitoring mechanism in baselib

- debian/changelog
- openquake/hazardlib/pmf.py
- openquake/hazardlib/tests/pmf_test.py
Adds a new method to the PMF class that samples the data in the probability mass function in proportion to the weights assigned to each element by the pmf.
> Adds sample method to PMF class

- openquake/hazardlib/gsim/base.py
- openquake/hazardlib/tests/gsim/base_test.py
This is to support https://bugs.launchpad.net/oq-engine/+bug/1471505. The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/360
> Added a forbid_instantiation context manager

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/source/base.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
This is needed for https://bugs.launchpad.net/oq-engine/+bug/1463057.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/367/
> Calculation times

- openquake/baselib/runtests.py
- openquake/baselib/testloader.py
- setup.py
This should help the testing on Red Hat.
> Enabled python setup.py test

- .travis.yml
- openquake/baselib/general.py
- openquake/baselib/python3compat.py
- openquake/hazardlib/gsim/base.py
The changes here are  needed by risklib. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/383/
This is all part of https://bugs.launchpad.net/oq-engine/+bug/1470396.
> More work on Python 3 support

- openquake/hazardlib/gsim/base.py
This is useful for debugging and needed for https://bugs.launchpad.net/oq-engine/+bug/1474443.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/390/
> Added a base __repr__ to GSIMs

- openquake/hazardlib/geo/geodetic.py
- openquake/hazardlib/tests/geo/geodetic_test.py
Needed to implement https://bugs.launchpad.net/oq-engine/+bug/1472252. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/393/
> Changed get_closest to return the distance too

- openquake/hazardlib/tests/gsim/check_gsim.py
Workaround for something that looks like a bug in the clock.
> Fixed windows issue with time_spent=0

- MANIFEST.in
> Included .hdf5 files in the MANIFEST

- .travis.yml
- openquake/baselib/general.py
For some reason it does not work with ``parallel`` (I get a command not found).
I have removed some bad doctests depending on the ordering of a dictionary.
> Added --with-doctest option to .travis.yml

- debian/changelog
- openquake/hazardlib/gsim/atkinson_boore_2003.py
Fixes https://github.com/gem/oq-engine/issues/1892.
> Atkinson boore2003 s slab nshmp2008 fix

- rpm/makerpm.sh
Small fix to align the script with risklib and engine
> rpm: makerpm allow cleanup before build

- openquake/baselib/hdf5.py
- openquake/baselib/performance.py
- openquake/baselib/tests/performance_test.py
- openquake/hazardlib/geo/mesh.py
- openquake/hazardlib/gsim/abrahamson_2014.py
- openquake/hazardlib/gsim/base.py
See https://github.com/gem/oq-risklib/issues/539. The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/429/
> Save the performance info directly in HDF5 format

- openquake/hazardlib/site.py
- openquake/hazardlib/tests/site_test.py
This is a helper method used in the ClassicalTiling calculator.
> Added SiteCollection.split_in_tiles method

- debian/changelog
- openquake/hazardlib/gsim/gsim_table.py
- openquake/hazardlib/tests/gsim/gsim_table_test.py
This is quite useful in tests, when one wants to specify paths relative to the current test directory.
There are also a few PEP 8 fixes.
> Made GMPETable smart enough to understand relative paths

- setup.py
> setup.py: psutil 2.2.* works and is needed now

- debian/changelog
- doc/mfd.rst
- openquake/hazardlib/mfd/__init__.py
- openquake/hazardlib/mfd/arbitrary_mfd.py
- openquake/hazardlib/tests/mfd/arbitrary_test.py
This PR adds a new type of magnitude frequency distribution known as an Arbitrary MFD, in which the magnitudes and rates are input as a pair of lists.
> Implements arbitrary mfd class

- packager.sh
> packager: missing upgrade for pkgbuild target added

- debian/changelog
- debian/control
- debian/rules
- packager.sh
Backported trusty hdf5 library and python-h5py for precise.
> Precise backport

- debian/control
Fixes an issues with nighlty packages always using precise rules.
> debian/control: add lsb_release

- debian/changelog
- openquake/hazardlib/calc/gmf.py
This is preliminary to https://github.com/gem/oq-risklib/issues/784.
> Refactored the GmfCalculator

- debian/changelog
- debian/rules
- packager.sh
https://ci.openquake.org/job/zdevel_oq-hazardlib/553/parameters/
> deb: add support for Ubuntu 16.04

- debian/changelog
- openquake/hazardlib/site.py
- openquake/hazardlib/tests/acceptance/_peer_test_data.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
- openquake/hazardlib/tests/site_test.py
The need for it was artificial and was causing trouble for people not setting the ID.
> Removed the .id attribute from the Site class

- openquake/hazardlib/calc/hazard_curve.py
This was merged at the wrong moment by Valerio, reverted, and not it is back.
PS: Valerio don't merge this!
> Restored the change ~->-

- debian/changelog
- openquake/baselib/hdf5.py
This is needed for https://github.com/gem/oq-engine/pull/2109.
> Fixed the serialization on HDF5 of dictionaries with keys containing slashes

- openquake/hazardlib/source/base.py
In preparation for the work on the Japan model, https://github.com/gem/oq-engine/issues/2099. Companion of https://github.com/gem/oq-engine/issues/2121
> Renamed trt_model_id -> src_group_id

- openquake/baselib/general.py
- openquake/baselib/hdf5.py
- openquake/baselib/python3compat.py
- openquake/hazardlib/geo/geodetic.py
- openquake/hazardlib/geo/surface/complex_fault.py
- openquake/hazardlib/mfd/youngs_coppersmith_1985.py
- openquake/hazardlib/site.py
- openquake/hazardlib/source/simple_fault.py
This is needed for https://github.com/gem/oq-engine/pull/2127
> Support for the Python 3 migration

- .travis.yml
This is an improvements compared to previous wheels since now they includes statically linked libraries (libgeo, libhdf5)
> Use our binary wheels with Travis

- speedups/geodeticmodule.c
- speedups/geoutilsmodule.c
Closes #476 
CI/Py2.7: https://ci.openquake.org/job/zdevel_oq-hazardlib/609/
Py3 on Travis
> Python3 compatibility for speedups

- debian/changelog
- openquake/baselib/python3compat.py
> Fixed the encode/decode functions in baselib.python3compat

- openquake/baselib/general.py
This is needed to export the IMT levels.
> Made DictArrays serializable to HDF5

- openquake/baselib/general.py
- openquake/baselib/hdf5.py
- openquake/baselib/performance.py
- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/probability_map.py
- openquake/hazardlib/source/area.py
- openquake/hazardlib/stats.py
- openquake/hazardlib/tests/stats_test.py
This is needed for https://github.com/gem/oq-engine/issues/2180. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/616/
> Added a facility to compute mean and quantiles for probability maps

- openquake/hazardlib/calc/hazard_curve.py
This is the companion of https://github.com/gem/oq-engine/pull/2202.
> Moved the contextmanager GroundShakingIntensityModel to hazardlib

- openquake/hazardlib/calc/filters.py
- openquake/hazardlib/tests/calc/filters_test.py
This is needed for https://github.com/gem/oq-engine/pull/2210.
> Made the filters pickleable

- packager.sh
> Copy deb files only if binaries are built in _pkgbuild_innervm_run

- openquake/baselib/sap.py
- openquake/hazardlib/calc/hazard_curve.py
This is needed for https://github.com/gem/oq-engine/pull/2253.
> Save the number of affected sites in monitor.calc_times

- openquake/__init__.py
Companion of https://github.com/gem/oq-engine/pull/2277
> Make the openquake namespace compatible with old setuptools

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
So that we can remove a few lines of code in the engine.
> Small refactoring

- debian/changelog
- openquake/hazardlib/calc/disagg.py
- openquake/hazardlib/site.py
Done in collaboration with M. Pagani.
> Support for the parameter iml_disagg in the engine

- openquake/baselib/hdf5.py
- openquake/hazardlib/calc/gmf.py
- openquake/hazardlib/geo/mesh.py
- openquake/hazardlib/geo/surface/base.py
- openquake/hazardlib/geo/surface/complex_fault.py
- openquake/hazardlib/geo/surface/planar.py
- openquake/hazardlib/source/non_parametric.py
- openquake/hazardlib/source/rupture.py
- openquake/hazardlib/tests/geo/surface/planar_test.py
So that we can remove the pickles from the datastore
> Support for serializing the ruptures to HDF5

- openquake/hazardlib/tests/geo/surface/multi_test.py
See https://ci.openquake.org/job/zdevel_win_oq-hazardlib/16
> Skipped multi_test.py on Windows

- debian/changelog
- openquake/hazardlib/site.py
This is the minimum fix that solves the issue. It would be nice to refactor completely SiteCollection and FilteredSiteCollection, but this is left for the future. Closes https://github.com/gem/oq-engine/issues/2306
> Fixed a 32 bit issue

- MANIFEST.in
- debian/changelog
This PR simplifies the MANIFEST and all the extensions under tests/ will be included
> Make sure all tests data is included in the py package

- debian/changelog
- openquake/hazardlib/calc/disagg.py
- openquake/hazardlib/calc/filters.py
- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/tests/acceptance/stochastic_test.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
- openquake/hazardlib/tests/source/base_test.py
This is not needed anymore, since the RtreeFilter supersedes it (the RtreeFilter reduces to the old filter when the flag rtree is false).
> Removed SourceSitesFilter

- openquake/baselib/general.py
- openquake/hazardlib/calc/filters.py
The warning must appear only once at import time.
> Put the rtree warning in the right place

- debian/changelog
- openquake/hazardlib/site.py
- openquake/hazardlib/tests/site_test.py
Closes https://github.com/gem/oq-engine/issues/2329. The tests in the engine are green too: https://travis-ci.org/gem/oq-engine/builds/177632355
> Made the FilteredSiteCollections serializable to HDF5

- debian/changelog
- openquake/baselib/general.py
This is used by the event based risk calculator.
> Added support for AccumDict of accumulators

- debian/changelog
- debian/control
- openquake/baselib/parallel.py
- openquake/baselib/tests/parallel_test.py
Close https://github.com/gem/oq-engine/issues/2389. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/674/
> Moved the parallelization library of the engine into baselib

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/source/base.py
- openquake/hazardlib/tests/calc/hazard_curve_new_test.py
- openquake/hazardlib/tests/source/base_test.py
The engine has the SourceModel concept that can be used for the same purpose.
> Remove SourceGroupCollection

- requirements-py27-linux64.txt
- requirements-py35-linux64.txt
Use the new wheelhouse and sync some deps.
> Use new wheelouse in requirements

- debian/changelog
- openquake/hazardlib/probability_map.py
- openquake/hazardlib/stats.py
Now they are all in hazardlib, not half in repo and half in another repo.
> Moved some functions to compute statistics from the engine to hazardlib

- openquake/hazardlib/source/complex_fault.py
Here I am just adding two attributes .start and .stop, all the logic is on the engine side.
> Support for splitting complex fault sources

- setup.py
Companion of https://github.com/gem/oq-engine/pull/2442
> Update classifiers in setup.py

- packager.sh
Sync'ed with https://github.com/gem/oq-engine/pull/2435
Tests: https://ci.openquake.org/job/zdevel_oq-hazardlib/682
> Update packager.sh and remove old code

- openquake/baselib/tests/general_test.py
- openquake/baselib/tests/performance_test.py
- requirements-py27-linux64.txt
- requirements-py35-linux64.txt
- setup.py
> Sync requirements with engine, remove old refs to risklib

- openquake/hazardlib/source/non_parametric.py
We want to avoid nested MultiSurfaces.
> Fixed management of MultiSurfaces in characteristic sources

- requirements-py27-linux64.txt
- requirements-py35-linux64.txt
- setup.py
See https://github.com/gem/oq-engine/pull/2460
> Cython isn't needed, get rid of it

- requirements-py27-macos.txt
As we do for linux, this is our reference
> Add requirements with local wheels copy for macOS

- README.md
- doc/development.md
- doc/requirements.md
> Documentation updates

- debian/changelog
- openquake/hazardlib/valid.py
This is useful to specify logarithmic ranges in the job.ini files. See the companion on the engine side.
> Introduced a logscale functionality

- debian/changelog
- openquake/hazardlib/nrml.py
- openquake/hazardlib/sourceconverter.py
- openquake/hazardlib/sourcewriter.py
This is fixing a very small bug. Tests are green. https://ci.openquake.org/job/zdevel_oq-hazardlib/696/
> 201701 bug fix writer

- doc/sphinx/openquake.baselib.rst
- doc/sphinx/openquake.hazardlib.calc.rst
- doc/sphinx/openquake.hazardlib.geo.rst
- doc/sphinx/openquake.hazardlib.mfd.rst
- doc/sphinx/openquake.hazardlib.rst
- doc/sphinx/openquake.hazardlib.scalerel.rst
- doc/sphinx/openquake.hazardlib.source.rst
> Documentation fixes

- debian/changelog
- openquake/baselib/parallel.py
Closes https://github.com/gem/oq-engine/issues/2467
> Made the parallelization library more robust against unexpected exceptions

- openquake/baselib/parallel.py
- openquake/baselib/performance.py
This allows for a simplification on the engine side.
> Save data transfer information automatically when a bunch of tasks complete

- openquake/hazardlib/gsim/megawati_pan_2010.py
> Removed a debugging print in MegawatiPan2010

- debian/changelog
- openquake/hazardlib/calc/disagg.py
- openquake/hazardlib/calc/filters.py
- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/gsim/base.py
- openquake/hazardlib/site.py
- openquake/hazardlib/tests/calc/hazard_curve_new_test.py
- openquake/hazardlib/tests/calc/hazard_curve_test.py
- openquake/hazardlib/valid.py
Everything relating to distance filtering (IntegrationDistance, get_distances, get_closest,...) has been moved in the module calc.filters.
> Refactored the filtering mechanism

- debian/changelog
- openquake/hazardlib/tests/source_model/alternative-mfds.xml
- openquake/hazardlib/tests/source_model/alternative-mfds_4test.xml
- openquake/hazardlib/tests/source_model/area-source.xml
- openquake/hazardlib/tests/source_model/characteristic-source.xml
- openquake/hazardlib/tests/source_model/complex-fault-source.xml
- openquake/hazardlib/tests/source_model/mixed.xml
- openquake/hazardlib/tests/source_model/nonparametric-source.xml
- openquake/hazardlib/tests/source_model/point-source.xml
- openquake/hazardlib/tests/source_model/simple-fault-source.xml
- openquake/hazardlib/tests/source_model/source_group_collection.xml
- openquake/hazardlib/tests/sourcewriter_test.py
This part was missing when I did the previous work of moving the hazard part of NRML into hazardlib.
> Copied sourcewriter_test.py and related files from the engine

- debian/changelog
- openquake/hazardlib/sourceconverter.py
Fixes the bug reported here: https://groups.google.com/d/msg/openquake-users/EO8rw5_dOhM/X3P1iD5BAgAJ
> Fixed splitting bug for YoungsCoppersmith1985MFD

- openquake/baselib/hdf5.py
This is needed for the companion PR on the engine.
> Moved the `set_nbytes` functionality into `baselib.hdf5.File`

- openquake/hazardlib/calc/gmf.py
Thanks to the simplification in https://github.com/gem/oq-engine/pull/2640 this complication is not needed anymore.
> Removed the salt from the GmfComputer

- debian/changelog
- openquake/hazardlib/calc/gmf.py
- openquake/hazardlib/tests/calc/gmf_test.py
Closes https://github.com/gem/oq-engine/issues/2643
> Added some validation to the GmfComputer inputs

- debian/changelog
- openquake/hazardlib/source/rupture.py
Closes https://github.com/gem/oq-engine/issues/2599.
> Fixed the serialization of NonParametricProbabilisticRuptures

- openquake/baselib/hdf5.py
- openquake/baselib/parallel.py
- openquake/hazardlib/geo/mesh.py
- openquake/hazardlib/source/__init__.py
- openquake/hazardlib/source/rupture.py
- openquake/hazardlib/sourceconverter.py
- openquake/hazardlib/tests/acceptance/peer_test.py
- openquake/hazardlib/tests/calc/hazard_curve_new_test.py
- openquake/hazardlib/tests/gsim/base_test.py
- openquake/hazardlib/tests/source/non_parametric_test.py
- openquake/hazardlib/tests/source/rupture_test.py
The goal is to make the serialization to HDF5 simpler. This is a preliminary step for https://github.com/gem/oq-engine/issues/2645
> Refactored the Rupture classes

- debian/changelog
- openquake/baselib/parallel.py
This is a first version, tested only on the demos. Here is an example of usage, assuming you have installed and configured properly the Grid Engine:
```
$ OQ_DISTRIBUTE=qsub oq engine --run demos/hazard/LogicTreeCase1ClassicalPSHA/job.ini
```
It works for me, but it seems to be ultra-slow, perhaps my configuration is bad.
> Experimental integration of the engine with the Grid Engine

- openquake/hazardlib/calc/gmf.py
Minor extension that will come handy in the future.
> Now the GmfComputer accepts an IntegrationDistance object in input

- debian/changelog
- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/probability_map.py
This will be used by the engine in a future pull request.
> Added `ProbabilityMap.convert2`

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/tests/calc/hazard_curve_new_test.py
As suggested by M. Pagani. Also fixed a small bug.
> Simplified the composition of SourceGroups assuming they are independent

- debian/changelog
- openquake/baselib/parallel.py
- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/nrml.py
- openquake/hazardlib/probability_map.py
- openquake/hazardlib/sourceconverter.py
- openquake/hazardlib/sourcewriter.py
- openquake/hazardlib/tests/source_model/source_group_collection.xml
Closes https://github.com/gem/oq-hazardlib/issues/631
> Introduced a grp_probability attribute

- openquake/hazardlib/calc/hazard_curve.py
- openquake/hazardlib/tests/calc/hazard_curve_new_test.py
And fixed the numbers in the tests.
> Fixed calc_hazard_curves for mutex sources

- debian/changelog
- openquake/hazardlib/geo/mesh.py
This was discovered by Catalina and Anirudh. The event based risk case_master test was giving strange warnings and the strike of the rupture was NaN. See https://github.com/gem/oq-engine/issues/2673.
> Fixed a numerical issue with sqrt of negative numbers

- debian/changelog
- openquake/hazardlib/geo/geodetic.py
- openquake/hazardlib/geo/utils.py
- openquake/hazardlib/tests/geo/geodetic_test.py
- openquake/hazardlib/tests/geo/utils_test.py
This is used by the engine to get the closest site parameter to each site.
> Using rtree to get the nearest geographic object

- openquake/hazardlib/geo/utils.py
Solves the problem in platforms without rtree.
> Fixed rtree import

- debian/changelog
- openquake/baselib/general.py
Not the best way, but the only one I know without involving the `git` command
Run: https://ci.openquake.org/job/zdevel_oq-hazardlib/757/
Closes https://github.com/gem/oq-engine/issues/2820
> Try to get git hash only if .git exists

- openquake/hazardlib/sourceconverter.py
Companion of https://github.com/gem/oq-engine/pull/2821.
> Moved split_filter_source in the engine

- openquake/hazardlib/valid.py
This is needed for https://github.com/gem/oq-engine/issues/2731.
> Disaggregation outputs

- openquake/baselib/parallel.py
- openquake/hazardlib/mfd/multi_mfd.py
- openquake/hazardlib/source/multi.py
This makes it possible to run Valerio's computation (https://github.com/gem/oq-engine/issues/2835).
> Added .modify method to the MultiMFD class
