gem/oq-hazardlib

openquake/hazardlib/general.py
This improves the code that retrieve the git version. It avoids the "-git" suffix if the git executable is installed on system but the oq-engine comes from packages.
=> Change git version code to avoid "-git" suffix if it's from packages

openquake/hazardlib/calc/gmf.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/tests/calc/gmf_test.py
Now it is possible to pass more than one GSIM instances. This is needed for https://bugs.launchpad.net/oq-engine/+bug/1400042. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/189/
=> Enhanced the GmfComputer

openquake/hazardlib/geo/mesh.py, openquake/hazardlib/tests/geo/mesh_test.py
See https://bugs.launchpad.net/oq-engine/+bug/1418961. The test passes in Ubuntu 12.04: https://ci.openquake.org/job/zdevel_oq-hazardlib/209/
=> Added a test sensitive to the underlying distance libraries

debian/changelog, openquake/hazardlib/__init__.py, packager.sh
- implemented the new guideline for version management, on master branch we will have always the release version after the current released.
- development packages will use ```~gem...``` suffix to be **lesser than** version **without** suffix (Debian - behavior for suffixes starting with ```~``` character).
- changelog and README are copied back to jenkins folders to be able to check them, an example at:
```jenkins@ci.openquake.org:jobs/zdevel_oq-hazardlib/workspace_new_vers_mgmt2_236```
=> New version management for development packaging.

openquake/hazardlib/source/area.py, openquake/hazardlib/tests/source/area_test.py
This PR attempts to fix a bug in the hypocentral depth distribution within the iter_ruptures() method of the area source.
Currently, when generating the ruptures a binding is taking place between the hypocentral depth used in each hypocentre in the rupture. https://github.com/gem/oq-hazardlib/blob/master/openquake/hazardlib/source/area.py#L127. This means that each time hc_depth changes, the hypocentral depth on all the previous ruptures are changed. This gives the unwanted, and incorrect, outcome that the hypocentral depth for all of the ruptures corresponds to the last value of the data PMF. This PR proposes the use of deepcopy(epicentre) to avoid binding the classes together.
Furthermore, the hypocentral depths of the resulting ruptures were not checked in the tests. The area_source …
=> Fixes CRITICAL area source hypocentral depth bug

packager.sh
This PR fixes `packger.sh` to run on CI hosted by an Ubuntu 14.04. It doesn't fix issues for creating packages in an Ubuntu 14.04 LXC. The LXC command line tools have changed a bit with LXC >= 1.0
Test for CI on 12.04: https://ci.openquake.org/job/zdevel_oq-hazardlib/244/
=> Make packager.sh compatible with Jenkins on Ubuntu 14.04

debian/changelog, openquake/hazardlib/gsim/base.py
Adds the term "hypo_loc" to the slots of the Rupture Context. This may eventually be filled with a tuple indicating the fractional along-strike and down-dip location of the hypocentre on the rupture plane.
Tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/258/
=> Adds hypo_loc to rupture context

packager.sh
This can be done using the `-L` flag with `packager.sh`
Old behaviour:
https://ci.openquake.org/job/zdevel_oq-hazardlib/259/
New behaviour:
https://ci.openquake.org/job/zdevel_oq-hazardlib_fast/4/
=> Allow packages build in an LXC

debian/changelog, openquake/hazardlib/calc/gmf.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/tests/calc/gmf_test.py
See https://bugs.launchpad.net/oq-engine/+bug/1438212. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/280/
This requires two companions on risklib and the engine to be merged: https://github.com/gem/oq-risklib/pull/218 and https://github.com/gem/oq-engine/pull/1739
=> Memory efficient representation for the GMFs

packager.sh
replacing "``-``" with "``+``" latest block isn't splitted in 2 different and comparable units.
=> change development version syntax to support multiple '~' characters

openquake/hazardlib/gsim/base.py
The Base Ground Shaking Intensity Model class uses the make_contexts function to produce the site, rupture and distance contexts. This PR splits each of these into separate functions (i.e. make_sites_context(), make_distances_context() and make_rupture_context()) to allow for the possibility of generating each of the different context objects. The make_contexts() function simply calls each of the new functions in turn.
=> Splits make contexts into three functions

openquake/hazardlib/source/characteristic.py, openquake/hazardlib/source/rupture.py
Adding two slots surface_node and surface_nodes so that it becomes possible to serialize to XML characteristic sources and non-parametric sources (https://bugs.launchpad.net/oq-engine/+bug/1456618). The functionality is implemented in the companion pull request https://github.com/gem/oq-risklib/pull/248.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/318
=> Source writer support

openquake/hazardlib/source/simple_fault.py
This is needed to simplify the implementation of https://bugs.launchpad.net/oq-engine/+bug/1457489 in risklib. This is the companion of https://github.com/gem/oq-risklib/pull/253.
The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/320
=> Simplified the management of hypo_list  and slip_list in SimpleFaultSource

debian/changelog
This is causing lots of
```
parsechangelog/debian: warning:     debian/changelog(l9): unrecognized line
LINE:  [Yen-Shin Chen]
parsechangelog/debian: warning:     debian/changelog(l9): unrecognized line
LINE:  [Yen-Shin Chen]
```
warnings on CI and produces a bad readme in packages
=> debian/changelog: wrong indentation

debian/changelog, openquake/hazardlib/source/rupture.py
Adds the term "rupture_slip_direction" to the slots of the Rupture class.
Tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/332/
=> Add rupture_slip_direction attribute

debian/changelog, openquake/hazardlib/source/rupture.py
This pull request fixes a bug in rupture, get_dppvalue.
Instead of self.fault_trace, it should be self.surface.get_resampled_top_edge().
to get the top edge of each rupture and used in multi-segment fault case.
The testing is for this is absent since there is no reference table available for multi-segment case. 
The test shows green:
https://ci.openquake.org/job/zdevel_oq-hazardlib/336/
=> Bug fixed in get_dppvalue for multi-segment fault case

openquake/hazardlib/geo/surface/base.py
This avoids the message
```
DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
mesh.depths[y_node][x_node])
```
Yen Shin, if you see such warnings, please take care of them, because I could not run your computation on my laptop, having a slightly newer version of numpy.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/349
=> Avoided a deprecation warning

openquake/hazardlib/site.py
This helps in discovering subtle bugs, when client code passes a filtered site collections instead of a complete one. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/351/
=> Added a check on filtered site collections

debian/changelog, debian/control
This is required for the GSIMs for Canada (https://github.com/gem/oq-hazardlib/pull/353).
The build is green: https://ci.openquake.org/job/zdevel_oq-hazardlib/359
=> Added dependency on h5py

openquake/hazardlib/site.py, openquake/hazardlib/tests/site_test.py
This is used in oq-lite (see https://github.com/gem/oq-risklib/pull/318) to compare the hazard site collection with the risk site collection. The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/364
=> Added equality of site collections

openquake/baselib/general.py, openquake/baselib/performance.py, openquake/baselib/python3compat.py, openquake/baselib/tests/general_test.py, openquake/baselib/tests/performance_test.py, openquake/hazardlib/calc/disagg.py, openquake/hazardlib/calc/gmf.py, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/calc/stochastic.py, openquake/hazardlib/gsim/__init__.py, openquake/hazardlib/gsim/abrahamson_2014.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/gsim/frankel_1996.py, openquake/hazardlib/gsim/megawati_pan_2010.py, openquake/hazardlib/tests/geo/utils_test.py, openquake/hazardlib/tests/gsim/utils.py
While we do not plan to migrate to Python 3 anytime soon, it is useful to introduce now an utility telling us how far we are from a Python 3-compatible syntax. Here is how to use it:
```bash
$ python -m openquake.baselib.python3compat openquake.hazardlib
.. several errors ...
Checked 248 ok, 7 wrong modules
```
We are actually already quite close to support Python 3. baselib and risklib are ready:
```bash
$  python -m openquake.baselib.python3compat openquake.baselib
Checked 7 ok, 0 wrong modules
$  python -m openquake.baselib.python3compat openquake.risklib
Checked 20 ok, 0 wrong modules
```
The other packages are not so bad:
```bash
$  python -m openquake.baselib.python3compat openquake.commonlib
Checked 82 ok, 7 wrong modules
$ python -m openquake.baselib.python3compat openquake.engine …
```
=> Initial support for Python 3 compatibility

debian/changelog, openquake/baselib/general.py, openquake/hazardlib/site.py, openquake/hazardlib/tests/site_test.py
`self.backarc[i]` and `self.sids[i]` are exchanged in `FilteredSiteCollection.__iter__` :-(
While I am at that, I am also adding a check for empty lists in the block splitting routine, to simplify the debugging of errors in the engine. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/365
=> Wrong order of the arguments

openquake/hazardlib/gsim/boore_atkinson_2008.py
Hi folks,
I'm Bruce Worden, the developer of ShakeMap. I encountered this bug while experimenting with this module. Essentially if dists.rjb and sites.vs30 are 2-dimensional, then the module won't work. The suggested fix appears to resolve the issue.
Best,
Bruce
=> Fix dimensionality bug in BooreAtkinson2008.

openquake/hazardlib/gsim/base.py
Adds two more terms into the __slots__ of the openquake.hazardlib.gsim.base.DistancesContext objects. These aren't really used in the hazardlib, but they are useful for compatibility with this PR on the OQ Ground Motion Toolkit https://github.com/GEMScienceTools/gmpe-smtk/pull/32
=> Adds 'azimuth' and 'hanging_wall' to DistancesContext

openquake/baselib/general.py
This will fix some errors on Windows:
```
Could not import openquake.calculators\tests.base_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.calc_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.classical_damage_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.classical_risk_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.classical_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.classical_tiling_test: ImportError: Import by filename is not supported.
Could not import openquake.calculators\tests.event_based_risk_test: ImportError: …
```
=> Make baselib portable to other OSes (aka Windows)

debian/changelog, openquake/hazardlib/mfd/base.py, openquake/hazardlib/scalerel/base.py, openquake/hazardlib/tests/mfd/base_test.py, openquake/hazardlib/tests/scalerel/asr_test.py, openquake/hazardlib/tests/scalerel/msr_test.py
For consistency with the GSIM class, adds the method `__str__` to the scalerel and mfd base classes
=> Adds __str__ method to scalrel and mfd base class

openquake/baselib/performance.py, openquake/baselib/tests/performance_test.py, openquake/hazardlib/calc/hazard_curve.py
This is needed for https://github.com/gem/oq-risklib/issues/411. Here I am introducing the concept of "children" of a monitor object. Calling `.flush` on the parent monitor automatically flushes all the children.
So in a worker we can generate several different children and have them flushed at once in the controller node.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/410
=> Refactored the PerformanceMonitor

debian/changelog, debian/control, packager.sh
Imposed version for python-h5py dependency, Ubuntu 12.04 will use backported version from GEM repository.
=> Custom h5py

openquake/baselib/performance.py, openquake/baselib/tests/performance_test.py
See https://github.com/gem/oq-risklib/issues/436. This is a first step towards the final goal of having all the data of a calculations (including logs and performance data) into a *single* .hdf5 file.
=> Removed the monitor_dir from the monitor

debian/changelog, openquake/hazardlib/source/area.py, openquake/hazardlib/source/base.py, openquake/hazardlib/source/characteristic.py, openquake/hazardlib/source/complex_fault.py, openquake/hazardlib/source/non_parametric.py, openquake/hazardlib/source/point.py, openquake/hazardlib/source/simple_fault.py, openquake/hazardlib/tests/source/base_test.py, openquake/hazardlib/tests/source/characteristic_test.py, openquake/hazardlib/tests/source/complex_fault_test.py, openquake/hazardlib/tests/source/simple_fault_test.py
Adds methods to three fault source classes (SimpleFaultSource, ComplexFaultSource, CharacteristicFaultSource) to modify/update the geometry of the source. These anticipate support for this option in the logic trees.
=> Adds geometry modifiers to fault sources

openquake/hazardlib/source/base.py
Master is broken: https://ci.openquake.org/job/master_oq-hazardlib/1505/console
I tried to keep the reference to the abstractproperty `MODIFICATIONS` in several ways, but sphinx has been complaining all the time, so at the end I gave up. Let's just remove the sphinx link.
=> Fixed a sphinx error

openquake/baselib/general.py, openquake/baselib/slots.py, openquake/hazardlib/geo/nodalplane.py, openquake/hazardlib/geo/polygon.py, openquake/hazardlib/geo/surface/planar.py, openquake/hazardlib/geo/utils.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/gsim/gsim_table.py, openquake/hazardlib/imt.py, openquake/hazardlib/mfd/evenly_discretized.py, openquake/hazardlib/mfd/truncated_gr.py, openquake/hazardlib/pmf.py, openquake/hazardlib/scalerel/ceus2011.py, openquake/hazardlib/scalerel/peer.py, openquake/hazardlib/site.py, openquake/hazardlib/source/area.py, openquake/hazardlib/source/base.py, openquake/hazardlib/source/characteristic.py, openquake/hazardlib/source/complex_fault.py, openquake/hazardlib/source/non_parametric.py, openquake/hazardlib/source/point.py, openquake/hazardlib/source/rupture.py, openquake/hazardlib/source/simple_fault.py, openquake/hazardlib/tests/gsim/check_gsim.py, openquake/hazardlib/tests/gsim/utils.py, openquake/hazardlib/tests/imt_test.py, openquake/hazardlib/tom.py
This is a preliminary step towards the elimination of `__slots__` (https://github.com/gem/oq-risklib/issues/541). By simply renaming `__slots__ -> _slots_` I am removing the "feature" and solving the error reported by an user. In subsequent pull requests I will remove `_slots_` completely. This must be done with care, because the `_slots_` attribute is used in the tests, when comparing two sources. A brutal removal of `_slots_` right now would break several tests.
The tests are running here: https://ci.openquake.org/job/zdevel_oq-hazardlib/426/
=> Removing `__slots__`

openquake/baselib/performance.py, openquake/baselib/tests/performance_test.py
I am improving the PerformanceMonitor in two ways:
1. I haved added a method .new which allows to instantiate a copy of a monitor which is not its child
2. the .flush method now works recursively on all children.
Feature 1) is needed when you want a decoupled monitor, to be flushed manually; feature 2) is needed in the opposite case, when one wants to make sure that all of the children are automagically flushed.
=> Better monitoring

debian/changelog, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/tests/calc/hazard_curve_test.py, openquake/hazardlib/tests/gsim/base_test.py
The goal is to compute the distances only once.
=> Move the rupture filtering inside the ContextMaker

debian/changelog, openquake/hazardlib/site.py
This was the source of the issue https://github.com/gem/oq-risklib/issues/596
The risk site collection was considered equal to the hazard one even it was not, since the differences in the site model parameters were ignored, and then the risk site collection was incorrectly used instead of the hazard one.
=> Fixed the SiteCollection equality check

openquake/hazardlib/geo/nodalplane.py, openquake/hazardlib/tests/geo/surface/planar_test.py
I found it useful when troubleshooting a large, complex source model to know what values were being rejected. Until I knew the "bad" rake was -180 degrees I couldn't figure out where the problem was.
=> Increased verbosity of nodalplane angle checks

debian/changelog, openquake/hazardlib/source/area.py, openquake/hazardlib/source/base.py, openquake/hazardlib/source/point.py
This is fairly minor. It looks better to move the management of the weight from oq-risklib to oq-hazardlib.
=> Added .weight and .num_ruptures to sources

openquake/hazardlib/gsim/gsim_table.py, openquake/hazardlib/tests/gsim/gsim_table_test.py, openquake/hazardlib/tests/gsim/utils.py
This avoids strange interferences between tests: now not only the case_18 tests in isolation, but it also runs when executed together with other tests. This is required for https://github.com/gem/oq-risklib/pull/617/
=> Made the GSIM.DEFINED_* class variables into instance variables

debian/changelog, openquake/baselib/general.py, openquake/hazardlib/site.py, openquake/hazardlib/tests/site_test.py
Will the following two methods it will be possible to store the site collection in the HDF5 datastore as a composite array and not as a pickled object. See https://github.com/gem/oq-risklib/issues/652.
=> Implemented methods to serialize the SiteCollection into HDF5

debian/changelog, openquake/hazardlib/gsim/base.py
This should save a significant amount of memory especially for the event based risk.
This is the companion of https://github.com/gem/oq-risklib/pull/698 and MUST be merged together.
=> Reduced the GMFs to 32 bits

setup.py
Upper limit is blocking port to Ubuntu 16.04. The first tests I did with Ubuntu 16.04 look fine, if we'll found issues with psutil > 3.0 we will need to fix the code anyway.
=> setup.py: remove upper limit in psutil

openquake/hazardlib/calc/gmf.py, openquake/hazardlib/geo/mesh.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/tests/geo/mesh_test.py
By removing the `idx` field from the composite array. I am also relaxing the check on `Mesh.__getitem__`. All that is needed for https://github.com/gem/oq-risklib/issues/743. This PR must be merged together with https://github.com/gem/oq-risklib/pull/744.
=> Simplified the output of the GmfComputer

debian/changelog, openquake/baselib/hdf5.py
This PR will be used later in oq-risklib to serialize the parameters of the job.ini file which currently as saved as attributes of the root of the HDF5 file. Using a table is a lot more readable.
=> Serialize a bunch of simple parameters in an HDF5 table

debian/changelog, openquake/baselib/hdf5.py, openquake/hazardlib/tests/site_test.py
This allows some simplification in the datastore that will be implemented in a second pull request.
=> Added a h5py.File subclass to manage the serialization of objects

debian/changelog, openquake/baselib/performance.py
=> Showing the `calc_id` in Monitor instances string representation

debian/changelog, openquake/hazardlib/imt.py
Catalina had a vulnerability function ' SA(1.0)', with an initial space, and was getting the error
```python
File "/home/michele/oqcode/oq-risklib/openquake/calculators/base.py", line 428, in read_risk_data
self.load_riskmodel()  # must be called *after* read_exposure
File "/home/michele/oqcode/oq-risklib/openquake/calculators/base.py", line 385, in load_riskmodel
self.oqparam.set_risk_imtls(rmdict)
File "/home/michele/oqcode/oq-risklib/openquake/commonlib/oqvalidation.py", line 243, in set_risk_imtls
from_string(imt)  # make sure it is a valid IMT
File "/home/michele/oq-hazardlib/openquake/hazardlib/imt.py", line 45, in from_string
period = float(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```
With this pull request the error become clear:
```python …
```
=> Improved the validity check on the Intensity Measure Type

openquake/baselib/hdf5.py, openquake/hazardlib/gsim/base.py
This should have been done from the beginning, but I was under the misconception that the `h5py.special_dtype(vlen=bytes)` was not understood by numpy. Instead, it is a perfectly valid dtype so there is no reason not to use it.
The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/517/
=> Saved LiteralAttrs as variable length byte strings

debian/changelog, openquake/baselib/hdf5.py
This is needed to store big sequences of objects in HDF5 format. The problem is that HDF5 truncated big binary blobs, so that they cannot be read back and unpickled. This is the cause of issue https://github.com/gem/oq-risklib/issues/639, when storing the ruptures.
=> Added a class PickleableSequence

debian/changelog, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/tests/calc/hazard_curve_test.py
For a long time now, the rupture filtering has been done when computing the distances, in the lines
```python
try:
sctx, rctx, dctx = cmaker.make_contexts(
s_sites, rupture)
except FarAwayRupture:
continue
```
However, the was still a `rupture_site_filter` in the signature of the function, never used by the engine.
I am removing that remnant of the past. Also, there is a minor refactoring of the part doing the aggregation of the hazard curves.
=> Small simplification of hazard_curves_per_trt

openquake/hazardlib/calc/gmf.py
The line `eids = get_array(events, sample=rlz.sampleid)['eid']` is what is needed to have the sampling feature back. See the companion in risklib https://github.com/gem/oq-risklib/pull/815.
=> Restored the sampling feature in the event based calculator

debian/changelog, openquake/hazardlib/calc/__init__.py, openquake/hazardlib/calc/hazard_curve.py
This was deprecated 18 months ago and it is time for it to go, with the coming of engine 2.0.
=> Removed the deprecated function `hazard_curve.hazard_curves`

openquake/hazardlib/calc/hazard_curve.py
This is needed to normalize the headers of the CSV files exported by the engine.
=> Renamed ~->-

openquake/hazardlib/calc/hazard_curve.py
This is needed to normalize the headers of the CSV files exported by the engine.
=> Revert "Renamed ~->-"

openquake/hazardlib/tests/gsim/gsim_table_test.py
The file was generated in the same folder as the test, this breaks test in some configurations (Windows, /opt)
=> Save test generated hdf5 in TEMP

debian/changelog, openquake/baselib/general.py, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/probability_map.py
... and moved it inside baselib.general. The concept of a DictArray is general and not tied to the Intensity Measure Types and Levels. In particular, in the engine it is also useful for the loss ratios per loss type. The previous name was too specific.
=> Renamed Imtls -> DictArray

debian/changelog, openquake/hazardlib/source/simple_fault.py
Thie pull request fixes the problem caused by the rupture counts in simple fault while multiple hypocenters and slip direction is set up for near-fault directivity assessment. 
The test shows green:
https://ci.openquake.org/job/zdevel_oq-hazardlib/608/
=> Fix rupture count in simple fault for near-fault directivity case

debian/changelog, openquake/baselib/hdf5.py
This should help Paolo: unserializing IMTLs was not working on QGIS.
=> Replaced pydoc.locate with a call to importlib to work around a QGIS issue

debian/changelog, openquake/baselib/sap.py, openquake/baselib/tests/sap_test.py
This is the right place, since it is useful also for hazardlib.
=> Moved the simple argument parser from commonlib to baselib

openquake/baselib/hdf5.py
When creating a dataset the values should be initialized to zero, not left as garbage. This is required for 
https://github.com/gem/oq-engine/pull/2197. The tests are green: https://ci.openquake.org/job/zdevel_oq-hazardlib/621/
=> Use a default fillvalue of zero

openquake/baselib/general.py, openquake/baselib/python3compat.py
It can be removed; the only trick is to make sure that the name of each datatype is converted with `str` (i.e. to bytes in Python 2 and to unicode in Python 3).
=> Removed python3compat.dtype

openquake/hazardlib/calc/gmf.py
Now it has a method `._compute(seed, gsim, num_events, imt)` and it is possible to compute the GMFs for a specific IMT. This is needed for https://github.com/gem/oq-engine/issues/2252. Also, the GMFComputer is now ready to receive high level ruptures like the ones coming from the engine.
=> Minor extension of the GmfComputer

openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/hazard_curve.py
By default there is no filtering, as in the past. If you want filtering, pass a SourceSitesFilter instance.
=> Fixed the filtering in calc_hazard_curves

openquake/hazardlib/probability_map.py
As a consequence of this bug, the classical_risk calculator is giving bogus results. See the companion on the engine.
=> Fixed ProbabilityMap.convert

.travis.yml, requirements-py27-linux64.txt, requirements-py35-linux64.txt
This wheels are experimental, but should work. These are not generated automatically because .so lib requires some patchwork using `patchelf`:
```bash
patchelf --set-rpath \$ORIGIN/.libs --force-rpath _wrapper_lib.so
```
An mock extension is used to be compatible with the `manylinux1` profile.
=> Use rtree wheels made by us

debian/changelog, openquake/hazardlib/calc/filters.py
This is mostly for the benefit of Mac users, since installing rtree there can be nontrivial.
=> Made the RtreeFilter optional, i.e. used only if the rtree library is available

openquake/hazardlib/source/area.py, openquake/hazardlib/source/point.py
Yesterday a computation by Graeme (PACNW) involving only point sources spawned only 48 tasks. This because the weight of the model was small. Point sources must be heavier to produce more tasks and to make better usage of our cluster, because the computation was heavy indeed. Several tests with different models show that weight larger than before has the additional benefit of making more uniform the tasks even in presence of fault sources. Therefore I am increasing the relative weight of point sources (and area sources) with respect to fault sources/characteric sources by a factor of 4.
=> Increased the weight of point source ruptures

openquake/hazardlib/calc/disagg.py, openquake/hazardlib/tests/calc/disagg_test.py
Moved `_collect_bins_data` from the engine and renamed the `_collect_bins_data` in hazardlib as `_collect_bins_data_old`. In a future pull request the duplication will be removed. At least now it is all in the same place and more visible.
=> Started some refactoring work on disaggregation

debian/changelog, openquake/hazardlib/geo/geodetic.py, openquake/hazardlib/geo/mesh.py, openquake/hazardlib/geo/polygon.py, openquake/hazardlib/geo/surface/base.py, openquake/hazardlib/source/rupture.py, openquake/hazardlib/tests/geo/geodetic_test.py, openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
Having removed the speedups, it is easy to optimize the distance computations so that we are faster than before while remaining pure Python. The trick is on the function `pure_distances`: there is an `if len(mlons) < len(slons)` that makes sure that the short loop in made in Python and the long loop in numpy (before it was the opposite).
Here are some numbers for a computation dominated by `make_context` (a reduces classical PSHA USA model with 1000 sites) which is representative of the worst case scenario:
```
master
making contexts  1,041 s
total runtime 275s
no-speedups
making contexts  1948 s
total runtime 334s
no-speedups-2
making contexts  1,032 s
total runtime 256s
```
Most large calculations are dominated by the PoEs computation, not by `making context`, so the distance …
=> Optimized the distance computations

debian/control
Now we are on pure python. With the default one (any) the packages are built as binary packages.
We do the same in the engine control: https://github.com/gem/oq-engine/blob/master/debian/control#L10
https://ci.openquake.org/job/zdevel_oq-hazardlib/657/
=> Force deb arch to all

rpm/makerpm.sh, rpm/python-oq-hazardlib.spec.inc
This PR adds two features:
- Generation of a "for release" RPM package is fully automatic now (as it was for "master" packages) using the `-r N` flag where N is the number of the package release (1, 2...)
- A custom version, which includes the git short commit, is put in the `__init.py__`
Test: https://ci.openquake.org/job/redhat_oq-hazardlib/50/
=> Automatic "for release" RPM generation and custom git version in __init.py__

debian/changelog, openquake/hazardlib/geo/surface/planar.py, openquake/hazardlib/tests/geo/surface/planar_test.py
The current version of the ry0 calculator for the planar fault uses the method in the base surface class, which relies on the creation of the mesh to determine the "average strike". At best this is unnecessary (the actual true strike is known from the corner points) and at worst this fails if the plane distorts such that a rectangular mesh cannot be created. This PR removes the call to the mesh and uses the strike directly.
=> Planar ry0 fix

debian/changelog, openquake/hazardlib/calc/disagg.py, openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/gmf.py, openquake/hazardlib/calc/stochastic.py, openquake/hazardlib/tests/calc/disagg_test.py, openquake/hazardlib/tests/calc/gmf_test.py, openquake/hazardlib/tests/calc/stochastic_test.py
From the point of view of the engine the `RuptureSitesFilter` class is redundant since it is never used: the rupture filtering is done during the calculation, when `make_contexts` is called. Also, the engine has a lot of filtering tests that are better than the one in hazardlib (which are mocking everything, wheres the tests in the engine are the real ones), so even the tests are redundant. Here I am doing some cleanup.
The function `filter_sites_by_distance_to_rupture` is not removed, it has been there for years and it will keep staying, so the change will not break existing code using it (if any).
If the future a new kind of filtering will be used - i.e. Marco Pagani's fantomatic distance-magnitude filtering - it will enter through `make_contexts` (the right place, just before the …
=> Removed redundant rupture_site_filter

openquake/hazardlib/geo/mesh.py, openquake/hazardlib/geo/surface/complex_fault.py, openquake/hazardlib/tests/geo/mesh_test.py
Moved `.get_joyner_boore_distance` from `Mesh` down to `RectangularMesh`, since it is used only there. Also, removed the call to `.flatten()` in `min_geodetic_distance`, since it is not needed. Removed `test_distance_to_2d_mesh` since we never need to compute the distance from a 2D mesh. The goal here is to reduce the number of use supported use cases, so that it becomes easier to optimize the distance calculation in a future pull request.
=> Minor simplification of `.get_joyner_boore`

openquake/hazardlib/calc/gmf.py
When the rupture comes from the engine, it has a `.seed` attribute and we can used it when the seed is not specified explicitly.
=> Refined the seed management in the GmfComputer

openquake/hazardlib/calc/gmf.py, openquake/hazardlib/site.py, openquake/hazardlib/tests/site_test.py
This method is not used anymore. Also, it is pretty dangerous performance-wise, so it is best to remove it to avoid the temptation to use it.
=> Removed SiteCollection.expand

openquake/hazardlib/geo/geodetic.py, openquake/hazardlib/tests/geo/geodetic_test.py
The npoints_towards() function does not ensure that the argument specifying the vertical distance (vdist) is turned into a float, and hence the output can be wrong. 
For example, npoints_towards(0,0,0,0,0,5,7) should give a list of 7 points equally spaced between 0 and 5km depth, but instead returns 7 points which are all (0.0, 0.0, 0.0)
=> vdist should be a float in npoints_towards function

debian/changelog, openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/hazard_curve.py
This allows further simplifications, since it will become possible to pass the filter from the controller node to the workers. The engine tests are green: https://travis-ci.org/gem/oq-engine/builds/177894918
=> Made RtreeFilter instances pickleable

openquake/hazardlib/calc/disagg.py, openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/source/base.py, openquake/hazardlib/tests/acceptance/peer_test.py, openquake/hazardlib/tests/acceptance/stochastic_test.py, openquake/hazardlib/tests/calc/hazard_curve_test.py, openquake/hazardlib/tests/source/base_test.py
Now the second argument is a SourceFilter instance instead of a SiteCollection. This is possible since the SourceFilter is pickleable thanks to https://github.com/gem/oq-hazardlib/pull/536. This means that two redundant arguments have been removed from `pmap_from_grp` that now only requires 7 arguments instead of 9. Futher simplifications will follow in future pull requests.
Notice that `calc_hazard_curves` works both with the new API and the old API, so that there is no breakage of the notebooks and the code by the hazard scientists.
PS: the tests involving mock sources have been removed (they are a maintenance burden) while the tests involving real sources have been kept.
=> Changed the API of `pmap_from_grp` and `calc_hazard_curves`

requirements-dev.txt, requirements-py27-linux64.txt, requirements-py35-linux64.txt
This PR adds a local copy of the setuptool wheel which is needed when --no-index is used during wheels installation.
=> Add missing setuptool wheel

debian/changelog, openquake/baselib/general.py
Daniele discovered that `subprocess.check_output` returns bytes in Python 3, so it has to be decoded.
=> Fixed a small Python 3 issue in git_suffix

debian/changelog, openquake/baselib/general.py, openquake/baselib/hdf5.py, openquake/baselib/tests/general_test.py, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/source/base.py
This is not needed by the engine, but it can be useful in the notebooks and in Python scripts. For instance, here is a classical calculator computing the hazard curves per each realization in less than 20 lines of code:
```python
import sys
import logging
from openquake.baselib import parallel
from openquake.hazardlib.calc.filters import SourceFilter
from openquake.hazardlib.calc.hazard_curve import calc_hazard_curves
from openquake.commonlib import readinput
def main(job_ini):
logging.basicConfig(level=logging.INFO)
oq = readinput.get_oqparam(job_ini)
sitecol = readinput.get_site_collection(oq)
src_filter = SourceFilter(sitecol, oq.maximum_distance)
csm = readinput.get_composite_source_model(oq).filter(src_filter)
rlzs_assoc = csm.info.get_rlzs_assoc()
sources = csm.get_sources()
for …
```
=> Made `calc_hazard_curves` parallelizable

setup.cfg
See: https://wheel.readthedocs.io/en/latest/#defining-the-python-version
=> Mark the binary dist as pure, universal python

debian/changelog, openquake/hazardlib/correlation.py
Recently a couple of risk users tried to use GMF-correlation, but discovered that the computation they wanted to do was impossibly slow. After inspection, the source of the problem has become clear to me: the correlation matrix is not cached, so it is recomputed million of times without need. This PR adds an IMT-specific cache for the correlation matrix.
=> Cached the correlation matrix

setup.py
Those imports were used at the time of C speedups.
Removing `import numpy` simplifies creation of `opt` like `site-packages` like we do in Windows.
https://ci.openquake.org/job/zdevel_oq-hazardlib/679/
=> Remove unused imports from setup.py

openquake/hazardlib/tests/calc/hazard_curve_test.py
A few weeks ago (see https://github.com/gem/oq-hazardlib/pull/542) I added the ability to compute hazard curves in parallel in hazardlib, but I had not time to add a test for it. I am closing the gap now. The test has been taken from the Hazard Modeler Toolkit. Having the functionality in hazardlib I propose to remove from the HMTK the files `hazard.py` and `hazard_test.py`, which have been broken for years (the tests are skipped).
=> Added a test case for calc_hazard_curves in parallel

debian/changelog, openquake/hazardlib/__init__.py, openquake/hazardlib/nrml.py, openquake/hazardlib/sourceconverter.py, openquake/hazardlib/sourcewriter.py, openquake/hazardlib/tests/valid_test.py, openquake/hazardlib/valid.py
Currently the Hazard Modeler Toolkit depends on the engine because it performs a few calls to libraries in commonlib. This is ugly:
1) the engine should only contains libraries related to the calculators; since the HTMK does not need the calculators it should not depend on the engine
2) hazardlib should be able to read and write sources without depending on the engine, it should be a self-contained library
The solution is to move a few files from the engine into hazardlib.
=> Move NRML libraries to hazardlib

openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/source/base.py, openquake/hazardlib/sourceconverter.py, openquake/hazardlib/sourcewriter.py, openquake/hazardlib/tests/calc/hazard_curve_new_test.py, openquake/hazardlib/tests/source/base_test.py
As requested by @mmpagani . This avoids the confusion of having two classes with the same name but slightly different. This change does not break the engine: https://travis-ci.org/gem/oq-engine/builds/192575307
=> Merged source.base.SourceGroup inside sourceconverter.SourceGroup

debian/changelog, openquake/hazardlib/tests/gsim/utils_test.py
Closes https://github.com/gem/oq-hazardlib/issues/568. Notice that it is possible to keep GSIMs undocumented, just start the module name with an underscore (private module).
=> Added a test to make sure that every GSIM is documented

debian/changelog, openquake/baselib/node.py, openquake/hazardlib/nrml.py
An user was using an invalid NRML exposure, but the error message was bad. This fixes the issue.
=> Improved the error message for XML files which are not NRML

debian/changelog, openquake/hazardlib/calc/filters.py
To avoid scaring the users. Missing rtree is not an issue.
=> Removed the warning about missing rtree

openquake/baselib/parallel.py
This is a preliminary step towards https://github.com/gem/oq-engine/issues/2497.
The idea is that tasks requiring a shared directory have an attribute `.shared_dir_on` which is true if the `shared_dir` is set in the engine side and false otherwise. If `.shared_dir_on` is false, such tasks are run through `concurrent.futures` and not through celery. Regular tasks (including legacy tasks) have no such attribute and they are run as before (i.e. with celery).
=> Recognize the task flag .shared_dir_on

openquake/hazardlib/stats.py, openquake/hazardlib/tests/stats_test.py
Closes https://github.com/gem/oq-hazardlib/issues/577
=> Using the same quantile algorithm both for weight=None and not None

openquake/hazardlib/sourceconverter.py
This class has nothing to do with hazardlib and everything to do with the logic trees, so it should go back to the oq-engine repository (from where it came).
=> Moved the SourceModel class back to the engine

openquake/baselib/general.py, openquake/baselib/parallel.py, openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/gmf.py, openquake/hazardlib/sourceconverter.py, openquake/hazardlib/tests/calc/hazard_curve_test.py, openquake/hazardlib/valid.py
I am adding a function `split_in_slices` that will be used by the engine to split large collections of sites in tiles. I am also adding a validation function `simple_slice` that will be used by the engine to select the slice of sites of interest (i.e. in the job.ini one can write sites_slice=0:100 and only the first 100 sites of the sites_csv file will be considered). There is also one renaming and a docstring fix.
=> Support for tiling

debian/changelog, openquake/hazardlib/calc/filters.py, openquake/hazardlib/calc/hazard_curve.py, openquake/hazardlib/gsim/base.py, openquake/hazardlib/tests/acceptance/stochastic_test.py, openquake/hazardlib/tests/calc/hazard_curve_test.py, openquake/hazardlib/valid.py
Once upon a time, the integration distance was a simple float, nowadays it is a dictionary `{tectonic_region_type: float}` which may have a `"default" key`, used to extract the distance for unspecified tectonic region types (i.e. the dictionary `{'default': 200}` gives a distance of 200 km to all tectonic region types).
With this pull request the integration distance will become an even more complex dictionary (which deserves to be of its own type)  which values can be list of pairs (magnitude, distance). From such pairs the `IntegrationDistance` object will build interpolating functions giving the distance for any magnitude. Such functions will be used in `ContextMaker.get_close` to filter the sites close to a given rupture.
A companion PR in the engine side will be open shortly.
=> Introduced a magnitude-dependent IntegrationDistance

.travis.yml, openquake/hazardlib/gsim/armenia_2016.py
A docstring in `openquake/hazardlib/gsim/armenia_2016.py` was broken but uncaught by Travis (it didn't test them) and Jenkins (was broken because other issues).
This broke opt builds.
This PR fixes the doctring, cleans pep8 issues and adds sphinx doc. generation in Travis
=> Fix armenia docstring and more

openquake/hazardlib/gsim/base.py
As requested by Graeme. I did a few tests on calculations dominated by the distance computations and I could not find any measurable difference with respect to the rjb distance (i.e. the times were the same within the statistics variation).
=> Using Rrup distance instead of Rjb as default

openquake/baselib/parallel.py
The doctest error in https://ci.openquake.org/job/master_oq-hazardlib/2293/ is due to the fact that `collections.Counter` has changed between Python 2 and Python 3; travis was happy but not Jenkins.
=> Fixed Jenkins

debian/changelog, openquake/hazardlib/calc/filters.py, openquake/hazardlib/site.py
Since the rtree filtering is ignoring the depths, it cannot be used when there is a non-trivial topography.
=> Enabled rtree filtering only if the site collection is at sea level

debian/changelog, openquake/hazardlib/geo/mesh.py, openquake/hazardlib/geo/surface/planar.py
In this way we reduce by half the memory and data transfer. Notice that `lon` and `lat` are already considered 32 bit floats in the site collection, so we are not losing any real precision.
=> Saved mesh as 32 bit floats

openquake/baselib/hdf5.py
There was a wrong `os.path.join` producing `\\` on Windows and causing the error  in https://ci.openquake.org/job/windows/job/master_oq-hazardlib/155/console/
Now the tests are green: https://ci.openquake.org/job/windows/job/zdevel_oq-hazardlib/4
=> Fixed XML to HDF5 tests

openquake/baselib/parallel.py
Before it was stored only for tasks with a weight. This affects the generation of the .rst report and `task_info` view. Here is an example for an event based calculation:
```
$ oq show task_info
======================= ===== ====== ===== === =========
operation-duration      mean  stddev min   max num_tasks
compute_ruptures        5.431 5.777  1.227 24  13       
compute_gmfs_and_curves 21    22     2.462 74  20       
======================= ===== ====== ===== === =========
```
Before the line for `compute_gmfs_and_curves` was missing, because there is an `if` that stores the information only if there is a weight.
=> Make sure that `task_info` is stored always

debian/changelog, openquake/hazardlib/geo/surface/planar.py
The clockwise order is needed for WKT MULTIPOLYGON strings.
We have to make sure this change does not break the behavior of other functionalities.
Fixes https://github.com/gem/oq-engine/issues/2618
=> In get_surface_boundaries order points in clockwise order

requirements-py27-linux64.txt, requirements-py27-macos.txt, requirements-py35-linux64.txt, requirements-py35-macos.txt, setup.py
See https://github.com/h5py/h5py/releases/tag/2.7.0
This affects https://github.com/gem/oq-libs too
MacOS: https://ci.openquake.org/job/macos/job/zdevel_mac_oq-hazardlib/15/
Windows: https://ci.openquake.org/view/Windows/job/windows/job/zdevel_oq-hazardlib/5/
=> Bump to h5py 2.7.0

CONTRIBUTORS.txt, openquake/hazardlib/geo/polygon.py, openquake/hazardlib/tests/geo/polygon_test.py
A Polygon object can now be alternatively instantiated by directly passing a WKT string in input. Overload is made using a separate (private) classmethod.
=> New constructor for Polygon class to parse a wkt polygon string

openquake/baselib/general.py
Fixes the error in https://ci.openquake.org/job/master_oq-engine/3415/console
=> Made safeprint more robust

requirements-py27-linux64.txt, requirements-py27-macos.txt, requirements-py35-linux64.txt, requirements-py35-macos.txt
Download the wheels from an ftp proxy on Linode instead of directly from our internal ftp. This reduces the load on our uplink and the cdn can provide stale cache if upstream is down.
=> Use CDN ftp mirror instead of upstream

openquake/hazardlib/probability_map.py
This is a minor improvement. Notice that now the property `nbytes` correctly returns 0 if the probability map is empty (before it raised a ValueError).
=> Added an exception AllEmptyProbabilityMaps

openquake/hazardlib/tests/__init__.py
This is to stop people from importing hazardlib functionalities into baselib of hmtk functionalities into hazardlib. The tower of dependencies must be kept stable under future refactoring. To file under the categories "sanity check" and "defensive programming".
=> Added an independence test

openquake/baselib/parallel.py
This gives more flexibility, even if do not need it now, since the configuration file is read at import time.
=> `shared_dir_on` is now a callable

debian/changelog, openquake/hazardlib/nrml.py, openquake/hazardlib/source/rupture.py, openquake/hazardlib/sourceconverter.py
Companion of https://github.com/gem/oq-engine/pull/2780. A `ses.xml` file can be parsed as follows:
```python
from openquake.hazardlib import nrml, sourceconverter
rupcoll = nrml.parse('ses.xml', sourceconverter.SourceConverter(rupture_mesh_spacing))
print(rupcoll)   # dictionary group_id -> ruptures
```
=> Extended the RuptureConverter to understand rupture collections

openquake/hazardlib/source/area.py, openquake/hazardlib/sourceconverter.py
Since the beginning of time hazardlib has considered AreaSources to be subclasses of PointSources. This makes no logical sense (area sources contain point sources, they are NOT point sources: they have no location!) and it is error prone: for instance any check `isinstance(src, PointSource)` is buggy, since `src` can be an AreaSource and not a PointSource as everybody would expect. For this reason the engine code is littered with checks like `src.__class__.__name__ == 'PointSource'` that are suboptimal. After several years, I am finally fixing this original sin. It was probably originated from the need to use some PointSource methods in the AreaSource class, but there is no need to inherit from it, we can just copy the needed methods, as I am doing in this pull request.
=> Area sources are not point sources

openquake/hazardlib/tests/geo/surface/base_surface_test.py
This is breaking `python3 -m compileall` in https://github.com/gem/oq-builders/pull/57
=> Fix a print that prevents compileall on Python 3
